services:
  - type: web
    name: coffeeshop
    runtime: python
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn ecommerce_project.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: coffeeshop-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: "False"
      - key: PORT
        value: 8001

databases:
  - name: coffeeshop-db
    databaseName: coffeeshop
    user: coffeeshop_user